"""
Reasoning Techniques Pattern Example
------------------------------------
This script demonstrates the Reasoning pattern (Chain of Thought):
Prompt -> Think Step-by-Step -> Final Answer

It simulates an agent that explicitly reasons before answering.
"""

import asyncio
import re


class ReasoningAgent:
    async def solve(self, problem: str) -> str:
        # Simulate the internal "thought process" of an LLM
        # In a real scenario, this would be generated by the model

        print(f"🤔 Problem: {problem}")
        print("🧠 Thinking...")

        reasoning_steps = []
        final_answer = ""

        if "apples" in problem:
            reasoning_steps = [
                "1. Identify initial quantity: 5 apples.",
                "2. Identify change: Ate 2 apples.",
                "3. Calculate remaining: 5 - 2 = 3.",
                "4. Identify change: Bought 3 more.",
                "5. Calculate final: 3 + 3 = 6.",
            ]
            final_answer = "6 apples"
        elif "prime" in problem:
            reasoning_steps = [
                "1. Definition of prime: Divisible only by 1 and itself.",
                "2. Check 10: Divisible by 2, 5. Not prime.",
                "3. Check 11: Divisible only by 1, 11. Prime.",
                "4. Check 12: Divisible by 2, 3, 4, 6. Not prime.",
                "5. Next prime after 7 is 11.",
            ]
            final_answer = "11"
        else:
            reasoning_steps = ["1. Analyze input.", "2. No specific logic found."]
            final_answer = "I don't know."

        # Display the Chain of Thought
        for step in reasoning_steps:
            await asyncio.sleep(0.5)  # Simulate thinking time
            print(f"   > {step}")

        print(f"💡 Final Answer: {final_answer}\n")
        return final_answer


async def main():
    agent = ReasoningAgent()

    await agent.solve("I have 5 apples, eat 2, then buy 3. How many now?")
    await agent.solve("What is the next prime number after 7?")


if __name__ == "__main__":
    asyncio.run(main())
