"""
Base Strategy Interface (IMP-011).

Abstract base class for investment strategies used in backtesting.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date, datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class SignalType(str, Enum):
    """Types of trading signals."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    STRONG_BUY = "strong_buy"
    STRONG_SELL = "strong_sell"


@dataclass
class StrategySignal:
    """A trading signal generated by a strategy."""

    signal_type: SignalType
    ticker: str
    date: date
    price: float
    confidence: float = 1.0  # 0.0 to 1.0
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal": self.signal_type.value,
            "ticker": self.ticker,
            "date": self.date.isoformat(),
            "price": self.price,
            "confidence": round(self.confidence, 3),
            "reason": self.reason,
            "metadata": self.metadata,
        }


@dataclass
class Position:
    """A position in a portfolio."""

    ticker: str
    shares: float
    entry_price: float
    entry_date: date
    current_price: float = 0.0

    @property
    def cost_basis(self) -> float:
        return self.shares * self.entry_price

    @property
    def market_value(self) -> float:
        return self.shares * self.current_price

    @property
    def gain_loss(self) -> float:
        return self.market_value - self.cost_basis

    @property
    def gain_loss_pct(self) -> float:
        if self.cost_basis == 0:
            return 0.0
        return (self.market_value - self.cost_basis) / self.cost_basis

    @property
    def days_held(self) -> int:
        return (date.today() - self.entry_date).days


class Strategy(ABC):
    """
    Abstract base class for investment strategies.

    Subclasses must implement:
    - should_buy(): Determine if a buy signal should be generated
    - should_sell(): Determine if a sell signal should be generated
    """

    def __init__(self, name: str, description: str = ""):
        self.name = name
        self.description = description
        self._signals: List[StrategySignal] = []

    @abstractmethod
    def should_buy(
        self,
        ticker: str,
        current_price: float,
        date: date,
        data: Dict[str, Any],
    ) -> Optional[StrategySignal]:
        """
        Determine if a buy signal should be generated.

        Args:
            ticker: Stock ticker symbol
            current_price: Current market price
            date: Current date
            data: Additional data (financials, indicators, etc.)

        Returns:
            StrategySignal if buy, None otherwise
        """
        pass

    @abstractmethod
    def should_sell(
        self,
        ticker: str,
        position: Position,
        current_price: float,
        date: date,
        data: Dict[str, Any],
    ) -> Optional[StrategySignal]:
        """
        Determine if a sell signal should be generated.

        Args:
            ticker: Stock ticker symbol
            position: Current position
            current_price: Current market price
            date: Current date
            data: Additional data (financials, indicators, etc.)

        Returns:
            StrategySignal if sell, None otherwise
        """
        pass

    def evaluate(
        self,
        ticker: str,
        current_price: float,
        date: date,
        data: Dict[str, Any],
        position: Optional[Position] = None,
    ) -> StrategySignal:
        """
        Evaluate the strategy for a given ticker.

        Args:
            ticker: Stock ticker symbol
            current_price: Current market price
            date: Current date
            data: Additional data
            position: Current position (if any)

        Returns:
            StrategySignal (BUY, SELL, or HOLD)
        """
        # Check for sell signal if we have a position
        if position:
            sell_signal = self.should_sell(
                ticker, position, current_price, date, data
            )
            if sell_signal:
                self._signals.append(sell_signal)
                return sell_signal

        # Check for buy signal
        buy_signal = self.should_buy(ticker, current_price, date, data)
        if buy_signal:
            self._signals.append(buy_signal)
            return buy_signal

        # Default to hold
        return StrategySignal(
            signal_type=SignalType.HOLD,
            ticker=ticker,
            date=date,
            price=current_price,
            reason="No signal generated",
        )

    @property
    def signals(self) -> List[StrategySignal]:
        """Get all signals generated by this strategy."""
        return self._signals.copy()

    def clear_signals(self) -> None:
        """Clear signal history."""
        self._signals.clear()

    def get_stats(self) -> Dict[str, Any]:
        """Get strategy statistics."""
        buy_signals = [s for s in self._signals if s.signal_type in (SignalType.BUY, SignalType.STRONG_BUY)]
        sell_signals = [s for s in self._signals if s.signal_type in (SignalType.SELL, SignalType.STRONG_SELL)]

        return {
            "name": self.name,
            "description": self.description,
            "total_signals": len(self._signals),
            "buy_signals": len(buy_signals),
            "sell_signals": len(sell_signals),
        }


__all__ = [
    "Strategy",
    "StrategySignal",
    "SignalType",
    "Position",
]
