"""
Research Phase Configuration

Defines the specific search queries and goals for each phase of the company research.
Updated to match the Enhanced Research Schema Design V2.
"""

RESEARCH_PHASES = {
    "00-Strategic-Context/01-Company-Overview": {
        "name": "Company Overview",
        "description": "Mission, Vision, History, Leadership",
        "query_templates": [
            "{company_name} mission vision values",
            "{company_name} company history timeline",
            "{company_name} leadership team ceo cmo",
            "{company_name} headquarters location employees",
        ],
        "min_sources": 3,
        "priority": 1,
    },
    "00-Strategic-Context/03-Key-News-Events": {
        "name": "Key News & Events",
        "description": "Recent press releases, mergers, acquisitions",
        "query_templates": [
            "{company_name} press releases 2024 2025",
            "{company_name} recent news acquisitions mergers",
            "{company_name} major partnerships 2024",
            "{company_name} crisis management news",
        ],
        "min_sources": 3,
        "priority": 2,
    },
    "00-Strategic-Context/04-Key-People": {
        "name": "Key People & Org Structure",
        "description": "Leadership, org chart, department heads, potential leads",
        "query_templates": [
            "{company_name} organizational structure chart",
            "{company_name} leadership team executives",
            "{company_name} department heads marketing sales technology",
            "{company_name} key employees linkedin",
            "{company_name} board of directors",
        ],
        "min_sources": 4,
        "priority": 2,
    },
    "01-Market-Intelligence/01-Market-Size-Growth": {
        "name": "Market Size & Growth",
        "description": "TAM/SAM/SOM, CAGR, financial projections",
        "query_templates": [
            "{industry} market size {country} 2024 2025",
            "{industry} industry growth rate {country} CAGR",
            "{industry} market forecast report 2030",
            "{industry} total addressable market {country}",
        ],
        "min_sources": 4,
        "priority": 3,
    },
    "01-Market-Intelligence/02-Key-Trends": {
        "name": "Key Trends",
        "description": "Emerging technologies, shifts in behavior",
        "query_templates": [
            "{industry} market trends {country} 2025",
            "{industry} emerging technologies 2024",
            "{industry} consumer behavior shifts {country}",
            "{industry} future outlook report",
        ],
        "min_sources": 4,
        "priority": 4,
    },
    "01-Market-Intelligence/03-Consumer-Behavior": {
        "name": "Consumer Behavior",
        "description": "How people buy, cultural nuances",
        "query_templates": [
            "{industry} consumer buying behavior {country}",
            "{industry} cultural trends affecting consumption {country}",
            "{industry} purchase decision factors",
            "{industry} consumer preferences {country} 2024",
        ],
        "min_sources": 3,
        "priority": 5,
    },
    "01-Market-Intelligence/04-Regulatory-Landscape": {
        "name": "Regulatory Landscape",
        "description": "Laws, compliance, political factors",
        "query_templates": [
            "{industry} regulatory landscape {country}",
            "{industry} compliance requirements {country}",
            "{industry} government regulations 2024",
            "{industry} legal challenges {country}",
        ],
        "min_sources": 2,
        "priority": 6,
    },
    "02-Target-Audience/01-ICP-Personas": {
        "name": "ICP Personas",
        "description": "Detailed profiles of ideal customers",
        "query_templates": [
            "{company_name} target audience demographics",
            "{industry} ideal customer profile examples",
            "who buys {company_name} products {country}",
            "{industry} customer psychographics",
        ],
        "min_sources": 4,
        "priority": 7,
    },
    "02-Target-Audience/02-Customer-Journey": {
        "name": "Customer Journey",
        "description": "Awareness -> Consideration -> Decision map",
        "query_templates": [
            "{industry} customer journey map",
            "{industry} buyer decision process",
            "{industry} customer touchpoints",
            "{company_name} customer experience reviews",
        ],
        "min_sources": 3,
        "priority": 8,
    },
    "02-Target-Audience/03-Pain-Points-Needs": {
        "name": "Pain Points & Needs",
        "description": "Specific problems and desired solutions",
        "query_templates": [
            "{industry} customer pain points {country}",
            "{industry} common customer complaints",
            "{industry} unmet customer needs",
            "{company_name} negative reviews analysis",
        ],
        "min_sources": 4,
        "priority": 9,
    },
    "03-Competitive-Landscape/01-Competitor-List": {
        "name": "Competitor List",
        "description": "Direct and indirect competitors",
        "query_templates": [
            "{company_name} top competitors {country}",
            "{company_name} alternatives and substitutes",
            "{industry} market leaders {country}",
            "emerging startups in {industry} {country}",
        ],
        "min_sources": 4,
        "priority": 10,
    },
    "03-Competitive-Landscape/02-Feature-Comparison": {
        "name": "Feature Comparison",
        "description": "Matrix of features vs competitors",
        "query_templates": [
            "{company_name} vs competitors features",
            "{company_name} product comparison chart",
            "{industry} product feature analysis",
            "{company_name} unique features vs market",
        ],
        "min_sources": 3,
        "priority": 11,
    },
    "03-Competitive-Landscape/03-Pricing-Analysis": {
        "name": "Pricing Analysis",
        "description": "Pricing tiers, models, and discounts",
        "query_templates": [
            "{industry} pricing models {country}",
            "{company_name} competitor pricing comparison",
            "{company_name} price increase history",
            "{industry} average price points {country}",
        ],
        "min_sources": 3,
        "priority": 12,
    },
    "03-Competitive-Landscape/04-Market-Share": {
        "name": "Market Share",
        "description": "Who owns the market?",
        "query_templates": [
            "{industry} market share {country} by company",
            "{company_name} market share history",
            "{industry} competitive landscape report 2024",
        ],
        "min_sources": 3,
        "priority": 13,
    },
    "04-Brand-Strategy/01-Positioning": {
        "name": "Positioning",
        "description": "USP, Value Prop, Brand Archetype",
        "query_templates": [
            "{company_name} brand positioning statement",
            "{company_name} unique selling proposition",
            "{company_name} brand archetype analysis",
            "{company_name} value proposition examples",
        ],
        "min_sources": 3,
        "priority": 14,
    },
    "04-Brand-Strategy/02-Messaging-Framework": {
        "name": "Messaging Framework",
        "description": "Key pillars, taglines, slogans",
        "query_templates": [
            "{company_name} marketing slogans taglines",
            "{company_name} brand messaging pillars",
            "{company_name} key marketing messages",
            "{company_name} advertising copy analysis",
        ],
        "min_sources": 3,
        "priority": 15,
    },
    "04-Brand-Strategy/03-Brand-Voice": {
        "name": "Brand Voice",
        "description": "Tone, personality, do's and don'ts",
        "query_templates": [
            "{company_name} brand voice tone",
            "{company_name} social media personality",
            "{company_name} brand guidelines pdf",
            "{company_name} communication style",
        ],
        "min_sources": 3,
        "priority": 16,
    },
    "05-Marketing-Execution/01-Channel-Strategy": {
        "name": "Channel Strategy",
        "description": "Priority channels (Social, SEO, Paid)",
        "query_templates": [
            "{company_name} marketing channels strategy",
            "{company_name} social media presence analysis",
            "{industry} best marketing channels {country}",
            "{company_name} paid advertising strategy",
        ],
        "min_sources": 4,
        "priority": 17,
    },
    "05-Marketing-Execution/02-Content-Plan": {
        "name": "Content Plan",
        "description": "Content pillars, formats, calendar ideas",
        "query_templates": [
            "{company_name} content marketing strategy",
            "{company_name} blog topics analysis",
            "{industry} content marketing trends 2024",
            "{company_name} social media content examples",
        ],
        "min_sources": 3,
        "priority": 18,
    },
    "05-Marketing-Execution/03-Funnel-Architecture": {
        "name": "Funnel Architecture",
        "description": "Lead magnets, nurture sequences",
        "query_templates": [
            "{company_name} sales funnel structure",
            "{company_name} lead generation strategies",
            "{industry} conversion optimization tactics",
            "{company_name} email marketing examples",
        ],
        "min_sources": 3,
        "priority": 19,
    },
    "06-Data-Room/01-Financials": {
        "name": "Financials",
        "description": "Revenue, funding, stock performance",
        "query_templates": [
            "{company_name} revenue 2023 2024",
            "{company_name} funding history crunchbase",
            "{company_name} stock price history",
            "{company_name} financial statements pdf",
        ],
        "min_sources": 3,
        "priority": 20,
    },
    "06-Data-Room/02-Statistics": {
        "name": "Statistics",
        "description": "Verified hard numbers and stats",
        "query_templates": [
            "{industry} {country} statistics 2024 verified",
            "{company_name} key performance indicators",
            "{industry} market research data points",
            "{company_name} growth statistics",
        ],
        "min_sources": 3,
        "priority": 21,
    },
    "07-Creative-Inspiration/01-Visual-Style": {
        "name": "Visual Style",
        "description": "Color palettes, imagery, design language",
        "query_templates": [
            "{company_name} brand visual identity",
            "{company_name} design system examples",
            "{company_name} website design analysis",
            "{industry} visual design trends 2024",
        ],
        "min_sources": 3,
        "priority": 22,
    },
    "07-Creative-Inspiration/02-Ad-Examples": {
        "name": "Ad Examples",
        "description": "Screenshots/descriptions of top ads",
        "query_templates": [
            "{company_name} best ad campaigns",
            "{company_name} facebook ads library",
            "{company_name} youtube commercials",
            "{industry} creative advertising examples",
        ],
        "min_sources": 3,
        "priority": 23,
    },
    "07-Creative-Inspiration/03-Viral-Campaigns": {
        "name": "Viral Campaigns",
        "description": "Case studies of successful campaigns",
        "query_templates": [
            "{company_name} viral marketing campaigns",
            "{industry} successful marketing case studies",
            "{company_name} social media viral hits",
            "{industry} guerrilla marketing examples",
        ],
        "min_sources": 3,
        "priority": 24,
    },
}
